### ISSUE TITLE
Edit / reorder

### ISSUE THREAD

**Issue by timothyaaron** [jovotech/ask-console-chrome-extension#2]
First, this is a great extension.
Second, I would love to be able to edit and/or re-order.

**Comment by jankoenig** [comment]
Thanks @timothyaaron! This is a great suggestion. We have our hands full with [Jovo Framework](https://github.com/jovotech/jovo-framework-nodejs/) `v2` right now, but will take a look after the launch.

**Comment by jankoenig** [comment]
Re-ordering now works with the latest update!
