### ISSUE TITLE
Ability to widen left-hand panel

### ISSUE THREAD

**Issue by habuma** [jovotech/ask-console-chrome-extension#6]
It would be very useful, especially when using the Voice & Tone tab to test SSML, to be able to widen the left-hand panel so that you can see a whole line of SSML without scrolling horizontally. 

I've been able to manually tweak this using Chrome's built-in developer tools, changing the CSS `width` of the element whose class is `.askt-input` to something like "1000px". But it'd be nice to somehow do that without such a brute-force approach.

**Comment by aswetlow** [comment]
Hey @habuma 

This should work already. Hover the thin grey line between the lighter grey and white panel. The col-resize cursor should appear.

**Comment by jankoenig** [comment]
Hey @habuma, my bad, I uploaded the updated version to the Chrome store, but forgot to publish it. Should be available now!

**Comment by habuma** [comment]
Yep. I reloaded my browser to get the latest extension installed and it works now! Thanks. (I'll close this issue.)
