### ISSUE TITLE
Alexa updated "test" console

### ISSUE THREAD

**Issue by benextleader** [jovotech/ask-console-chrome-extension#8]
Hi! Due to an update on the Test console looks like the extension stopped working.

Alexa added this function natively but yours are still better!

Pls, kindly consider fix it ;)

**Comment by aswetlow** [comment]
Hey @benextleader 

Weird. I tried the new functionality and it worked.
After enabling and disabling our extension I don't see the big plus button anymore. But our extension works as expected. 

What do you get?

**Comment by benextleader** [comment]
Hi Alex!

It's now working again. Sorry to bother you with this.

But yesterday it stopped working completely. I´ve uninstalled and installed
it back and it works fine now!

Best!

**Comment by aswetlow** [comment]
We did a few tests and our extension was broken with the new ASK Console feature. 

It's fixed and released now. You can download version 1.4 from the Chrome Webstore, or clone the repository.
https://chrome.google.com/webstore/detail/alexa-skills-kit-simulato/opjjjciodammljgdambcjmljkcjblkkk
